# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'projectX' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for projectX
  target 'projectXTests' do
    inherit! :search_paths
    # Pods for testing

pod 'Fabric', '~> 1.7.3'
pod 'Crashlytics', '~> 3.10.0'

  end

end

pod 'Firebase/Core'
pod 'Firebase/Performance'
